In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('Social_Network_Ads.csv')
df.head(4)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0

In [4]:
df.shape

(400, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [6]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [7]:
# In this dataset we can see that userid and gender is not that useful so we will focus on other two
x=df.iloc[:,2:4]
y=df.iloc[:,-1]

In [8]:
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [9]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [11]:
# feature Scaling

from sklearn.preprocessing import StandardScaler
ssc=StandardScaler()
x_train=ssc.fit_transform(x_train)
x_test=ssc.transform(x_test)

In [12]:
x_train

array([[ 1.8925893 ,  1.52189404],
       [ 0.1250379 ,  0.03213212],
       [ 0.9106163 , -1.31157471],
       [-1.34792161, -1.48684082],
       [-0.169554  , -0.58129926],
       [-0.56234321,  2.33980255],
       [ 1.0088136 , -1.19473064],
       [-0.75873781,  1.08372877],
       [ 2.1871812 , -1.04867555],
       [ 0.0268406 , -0.25997806],
       [-0.46414591, -1.1363086 ],
       [ 0.1250379 ,  0.03213212],
       [ 1.6961947 , -0.90262046],
       [ 1.1070109 , -0.90262046],
       [ 0.5178271 ,  1.22978386],
       [-1.05332971, -1.4576298 ],
       [-1.15152701, -1.54526286],
       [-0.0713567 ,  0.67477452],
       [ 0.4196298 , -0.46445519],
       [-0.2677513 , -0.25997806],
       [-0.85693511,  0.14897619],
       [ 0.0268406 ,  0.29503128],
       [ 0.7142217 , -1.28236369],
       [ 1.5979974 ,  1.11293979],
       [ 0.812419  , -1.36999675],
       [-1.44611891, -1.22394166],
       [-0.0713567 ,  0.14897619],
       [ 0.4196298 , -0.14313399],
       [-0.2677513 ,  0.03213212],
       [ 1.3034055 ,  2.22295848],
       [ 0.1250379 ,  0.76240757],
       [-1.34792161,  0.55793045],
       [ 1.9907866 ,  0.73319655],
       [-1.24972431, -1.39920777],
       [ 0.3214325 , -0.3184001 ],
       [-0.95513241,  0.55793045],
       [ 0.4196298 ,  0.29503128],
       [ 0.4196298 ,  1.11293979],
       [ 0.812419  ,  0.76240757],
       [ 0.9106163 ,  1.25899488],
       [-0.46414591, -1.22394166],
       [-1.83890811, -1.31157471],
       [ 1.1070109 ,  0.55793045],
       [-0.66054051, -1.60368489],
       [-0.75873781,  0.26582026],
       [ 1.0088136 ,  2.07690339],
       [-0.56234321,  1.37583895],
       [-0.0713567 ,  0.03213212],
       [-1.93710541,  0.47029739],
       [ 0.4196298 ,  0.26582026],
       [-1.05332971,  0.41187535],
       [ 0.2232352 , -0.14313399],
       [ 1.8925893 ,  0.11976517],
       [-1.15152701, -1.60368489],
       [-1.15152701,  0.29503128],
       [-0.85693511, -0.78577639],
       [-0.46414591,  2.31059153],
       [ 0.1250379 , -0.8149874 ],
       [ 1.5979974 ,  0.99609572],
       [-0.169554  , -1.07788657],
       [ 0.812419  , -1.10709759],
       [ 0.2232352 ,  2.1061144 ],
       [-0.0713567 , -0.23076704],
       [-0.85693511,  2.28138051],
       [-0.0713567 , -0.37682213],
       [-0.2677513 , -0.58129926],
       [ 0.4196298 , -0.49366621],
       [-0.2677513 , -0.93183148],
       [ 0.3214325 , -1.16551962],
       [ 0.2232352 ,  0.06134314],
       [-1.15152701, -1.60368489],
       [-0.66054051, -0.05550093],
       [-0.2677513 , -0.49366621],
       [-0.2677513 , -1.31157471],
       [-0.75873781,  0.55793045],
       [ 0.3214325 ,  0.06134314],
       [-0.95513241,  1.55110506],
       [ 0.812419  ,  0.35345332],
       [-1.54431621, -0.20155602],
       [ 0.7142217 , -1.39920777],
       [-0.75873781, -0.61051028],
       [-0.36594861, -1.31157471],
       [ 0.2232352 ,  0.14897619],
       [-0.56234321,  1.37583895],
       [-1.44611891,  0.35345332],
       [-1.15152701,  0.29503128],
       [ 1.0088136 ,  1.7847932 ],
       [ 2.0889839 ,  2.13532542],
       [-0.2677513 , -0.43524417],
       [-0.36594861, -0.78577639],
       [ 0.1250379 , -0.25997806],
       [-1.05332971,  0.76240757],
       [ 2.1871812 ,  0.38266434],
       [-1.34792161, -0.43524417],
       [ 1.9907866 ,  2.16453644],
       [ 1.4998001 ,  0.99609572],
       [-0.2677513 ,  0.26582026],
       [-0.169554  ,  0.85004063],
       [ 1.8925893 , -0.28918908],
       [-0.0713567 ,  1.96005931],
       [-0.46414591, -0.78577639],
       [ 0.3214325 ,  0.03213212],
       [ 1.4016028 , -1.42841878],
       [ 1.4016028 ,  2.33980255],
       [-0.0713567 ,  0.0029211 ],
       [-1.15152701,  0.41187535],
       [-1.15152701,  0.06134314],
       [-1.15152701, -0.52287722],
       [ 0.3214325 , -0.28918908],
       [-0.66054051, -0.11392297],
       [-0.0713567 ,  2.16453644],
       [ 0.0268406 , -0.25997806],
       [-0.66054051, -1.04867555],
       [ 0.4196298 ,  0.14897619],
       [ 0.812419  ,  1.37583895],
       [-0.169554  , -0.52287722],
       [ 0.0268406 ,  0.03213212],
       [ 1.1070109 ,  0.52871943],
       [ 1.8925893 , -1.07788657],
       [ 1.0088136 ,  1.98927033],
       [ 0.9106163 , -0.58129926],
       [-0.46414591, -0.02628992],
       [-0.0713567 ,  2.22295848],
       [-1.74071081,  0.35345332],
       [ 0.2232352 , -0.66893231],
       [-0.2677513 , -1.39920777],
       [-1.74071081, -0.99025351],
       [ 0.7142217 , -0.72735435],
       [-1.15152701, -0.78577639],
       [ 1.9907866 ,  0.90846266],
       [ 0.2232352 , -0.37682213],
       [ 0.0268406 ,  1.22978386],
       [-0.0713567 ,  0.29503128],
       [ 1.1070109 , -1.22394166],
       [-0.169554  ,  0.14897619],
       [ 0.3214325 ,  0.06134314],
       [-0.2677513 , -0.28918908],
       [ 0.5178271 ,  1.72637117],
       [ 0.3214325 ,  0.49950841],
       [ 0.0268406 ,  1.25899488],
       [ 1.9907866 , -1.36999675],
       [-1.15152701, -1.10709759],
       [-0.56234321, -1.51605184],
       [ 0.3214325 , -0.52287722],
       [-0.66054051, -1.51605184],
       [-0.2677513 ,  0.52871943],
       [ 1.0088136 , -1.01946453],
       [-1.05332971,  0.55793045],
       [-0.2677513 ,  0.79161859],
       [ 0.4196298 ,  0.09055416],
       [-1.64251351, -0.05550093],
       [ 0.3214325 ,  0.06134314],
       [-0.46414591, -0.28918908],
       [ 0.1250379 ,  1.87242626],
       [-0.95513241,  0.41187535],
       [ 0.812419  ,  0.52871943],
       [-1.34792161, -0.34761112],
       [-0.66054051,  1.40504997],
       [ 1.2052082 ,  0.52871943],
       [-1.74071081,  0.35345332],
       [-0.56234321,  1.90163728],
       [-1.74071081,  0.47029739],
       [-0.2677513 , -1.25315268],
       [-0.85693511, -0.78577639],
       [-1.64251351,  0.52871943],
       [-0.2677513 , -0.3184001 ],
       [ 0.7142217 , -1.10709759],
       [ 2.1871812 , -0.8149874 ],
       [-0.2677513 ,  0.61635248],
       [-0.2677513 , -0.75656537],
       [-1.93710541, -0.75656537],
       [ 0.4196298 ,  2.31059153],
       [ 0.7142217 ,  0.26582026],
       [ 0.2232352 , -0.28918908],
       [-1.34792161, -1.36999675],
       [-0.46414591, -0.55208824],
       [ 0.4196298 ,  0.0029211 ],
       [ 1.6961947 ,  1.75558219],
       [ 1.2052082 , -0.75656537],
       [ 1.0088136 ,  1.43426099],
       [-1.83890811,  0.17818721],
       [ 0.3214325 ,  0.06134314],
       [ 0.2232352 ,  0.03213212],
       [-1.05332971,  0.52871943],
       [-0.169554  ,  1.63873811],
       [-0.2677513 ,  0.14897619],
       [-0.2677513 , -0.34761112],
       [-0.36594861,  1.31741692],
       [-0.2677513 ,  0.09055416],
       [ 2.1871812 ,  1.11293979],
       [-1.24972431,  0.49950841],
       [-1.05332971, -0.46445519],
       [-1.64251351, -1.57447387],
       [-0.0713567 ,  0.11976517],
       [-0.2677513 , -0.90262046],
       [ 1.5979974 ,  0.0029211 ],
       [ 0.9106163 , -1.16551962],
       [ 0.0268406 , -0.58129926],
       [-0.2677513 ,  2.25216949],
       [-0.2677513 ,  0.20739823],
       [ 0.3214325 ,  0.26582026],
       [-0.0713567 , -1.07788657],
       [ 2.1871812 , -0.69814333],
       [-0.95513241, -0.3184001 ],
       [-1.44611891, -0.11392297],
       [-1.44611891, -0.20155602],
       [-0.75873781, -1.54526286],
       [-1.24972431, -1.07788657],
       [ 2.0889839 ,  0.38266434],
       [ 1.9907866 , -0.93183148],
       [-1.93710541,  0.35345332],
       [ 0.812419  , -0.3184001 ],
       [-1.05332971, -1.54526286],
       [ 1.9907866 , -0.66893231],
       [ 1.0088136 , -1.16551962],
       [ 1.1070109 , -0.14313399],
       [ 1.2052082 , -0.99025351],
       [ 1.4998001 ,  0.06134314],
       [ 0.2232352 , -0.37682213],
       [ 1.4016028 ,  1.2882059 ],
       [ 2.0889839 , -0.8149874 ],
       [-0.169554  , -0.20155602],
       [ 0.4196298 ,  0.99609572],
       [-0.0713567 , -0.52287722],
       [ 1.0088136 , -1.07788657],
       [ 2.0889839 , -1.19473064],
       [-0.0713567 ,  0.26582026],
       [ 0.2232352 , -0.25997806],
       [ 1.1070109 ,  0.11976517],
       [-1.24972431,  0.58714146],
       [-0.75873781, -1.60368489],
       [ 0.2232352 ,  0.23660925],
       [-1.34792161,  0.41187535],
       [ 0.0268406 , -0.58129926],
       [ 0.7142217 ,  1.7847932 ],
       [-1.64251351,  0.06134314],
       [-0.2677513 , -1.36999675],
       [-0.2677513 , -1.4576298 ],
       [-0.66054051,  0.55793045],
       [-0.75873781,  0.29503128],
       [ 0.9106163 , -0.66893231],
       [-1.05332971,  0.58714146],
       [-0.2677513 ,  0.06134314],
       [-0.75873781,  1.34662793],
       [ 0.1250379 ,  1.52189404],
       [-0.85693511,  0.38266434],
       [ 0.3214325 , -0.20155602],
       [ 1.0088136 ,  0.58714146],
       [ 0.0268406 , -0.3184001 ],
       [-0.56234321, -1.51605184],
       [ 0.1250379 ,  0.14897619],
       [-1.15152701,  0.3242423 ],
       [ 0.1250379 ,  1.05451775],
       [-1.54431621, -0.43524417],
       [-0.169554  ,  1.40504997],
       [ 2.1871812 , -0.8149874 ],
       [-0.95513241, -0.43524417],
       [ 1.3034055 ,  1.87242626],
       [ 1.1070109 , -1.22394166],
       [-0.169554  , -0.28918908],
       [ 1.794392  ,  0.99609572],
       [-1.05332971, -0.34761112],
       [-1.34792161, -1.10709759],
       [-0.36594861,  0.06134314],
       [-0.95513241, -1.10709759],
       [ 1.2052082 , -1.4576298 ],
       [-0.46414591, -0.84419842],
       [-0.85693511, -0.66893231],
       [-1.54431621, -1.51605184],
       [-0.75873781,  1.90163728],
       [ 0.9106163 ,  1.02530673],
       [ 0.812419  ,  0.26582026],
       [ 1.0088136 ,  1.87242626],
       [ 0.9106163 , -0.61051028],
       [ 1.1070109 ,  2.07690339],
       [-0.56234321,  0.87925164],
       [ 0.0268406 ,  0.03213212],
       [-1.83890811, -1.28236369],
       [-0.0713567 ,  0.20739823],
       [ 0.9106163 , -0.55208824],
       [ 0.2232352 , -0.37682213],
       [-0.169554  ,  1.6095271 ],
       [-1.74071081,  0.11976517],
       [-0.66054051, -0.34761112],
       [ 0.3214325 , -0.72735435],
       [ 0.4196298 , -0.46445519],
       [-0.95513241, -0.96104249],
       [ 0.1250379 ,  0.09055416],
       [-0.95513241,  0.44108637],
       [ 0.0268406 , -0.55208824],
       [ 0.9106163 , -0.78577639],
       [-0.0713567 ,  0.06134314],
       [ 1.1070109 , -0.99025351],
       [ 0.7142217 , -1.39920777],
       [-0.2677513 ,  0.06134314],
       [-1.34792161, -1.25315268],
       [-1.15152701, -1.01946453],
       [ 0.5178271 ,  1.84321524],
       [ 0.1250379 ,  0.20739823],
       [-0.56234321,  0.47029739]])

In [13]:
from sklearn.svm import SVC
svc=SVC(kernel='linear')
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [14]:
y_pred=svc.predict(x_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [15]:
# checking accuracy and classification report
from sklearn.metrics import accuracy_score,classification_report
print("Accuracy of the model is:- ",accuracy_score(y_test,y_pred)*100)

print(classification_report(y_pred,y_test))

Accuracy of the model is:-  86.0
              precision    recall  f1-score   support

           0       0.97      0.84      0.90        73
           1       0.68      0.93      0.78        27

    accuracy                           0.86       100
   macro avg       0.82      0.88      0.84       100
weighted avg       0.89      0.86      0.87       100

In [16]:
# Will take some different hyperparameters now
svc1=SVC(kernel='rbf',gamma=10,C=5)
svc1.fit(x_train,y_train)

SVC(C=5, gamma=10)

In [17]:
y_pred1=svc1.predict(x_test)
y_pred1

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [18]:
print(accuracy_score(y_pred1,y_test))

0.91

In [19]:
print(classification_report(y_pred1,y_test))

              precision    recall  f1-score   support

           0       0.95      0.91      0.93        66
           1       0.84      0.91      0.87        34

    accuracy                           0.91       100
   macro avg       0.90      0.91      0.90       100
weighted avg       0.91      0.91      0.91       100

In [20]:
# lets just check with polynomial kernel
svc2=SVC(kernel='poly',degree=4,gamma=10,C=5)
svc2.fit(x_train,y_train)
y_pred2=svc2.predict(x_test)
y_pred2

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1], dtype=int64)

In [21]:
print(accuracy_score(y_pred2,y_test))

0.77

In [22]:
print(classification_report(y_pred2,y_test))

              precision    recall  f1-score   support

           0       0.84      0.80      0.82        66
           1       0.65      0.71      0.68        34

    accuracy                           0.77       100
   macro avg       0.74      0.75      0.75       100
weighted avg       0.78      0.77      0.77       100

In [23]:
svc3=SVC(kernel='poly',degree=2,gamma=15,C=7)
svc3.fit(x_train,y_train)
y_pred3=svc3.predict(x_test)
y_pred3

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [24]:
print(accuracy_score(y_pred3,y_test))

0.79

In [25]:
svc4=SVC(kernel='poly',degree=3)
svc4.fit(x_train,y_train)
y_pred4=svc4.predict(x_test)
y_pred4

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0], dtype=int64)

In [26]:
print(accuracy_score(y_pred4,y_test))

0.85

In [27]:
print(classification_report(y_pred4,y_test))

              precision    recall  f1-score   support

           0       1.00      0.81      0.89        78
           1       0.59      1.00      0.75        22

    accuracy                           0.85       100
   macro avg       0.80      0.90      0.82       100
weighted avg       0.91      0.85      0.86       100

# ThankYou